name: CI - Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write  # GHCR 푸시용 권한

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    uses: nhnacademy-aiot2-lucky7/common-infra/.github/workflows/reusable-docker-publish.yml@main
    with:
      image-name: sensor-service
      use-github-token: true